language: node_js
node_js:
  - '13.5.0'
before_script:
  - 'npm run lint'
after_script:
  - 'istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec && cat ./coverage/lcov.info | ./node_modules/.bin/codecov'
notifications:
  email:
    on_success: never
    on_failure: never
deploy:
  provider: npm
  email: $EMAIL_ADDRESS
  api_key: $NPM_API_KEY
  on:
    tags: true
    all_branches: true
